services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sahil
      POSTGRES_PASSWORD: itsamemario
      POSTGRES_DB: universityDatabase