package com.example.project1.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
@Table(name = "enrollment")

/*Represents enrollment of a student in course in a system
* It is mapped to "enrollment" table in the database */
public class Enrollment {

    /* Primary Key for enrollment
    * It is auto-generated by using sequence generator*/
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Integer enrollment_id;

    /*The student associated with this enrollment
    * Many enrollment can belong to one student */
    @ManyToOne
    @JoinColumn(name = "student_id")
    StudentEntity student;

    /* The course associated with this enrollment
    * Many enrollment can be enrolled in one course*/
    @ManyToOne
    @JoinColumn(name = "course_id")
    CourseEntity course;
}
