package com.example.project1.entity;


import jakarta.persistence.*;
import lombok.*;

import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
@Table(name = "student")
/*Represents Student in a system
* It is mapped to "student" table in the database */
public class StudentEntity {

    /*Primary key
    * It is auto-generated by using sequence generator */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "student_seq")
    private Integer student_id;

    /* Name of the student*/
    private String name;

    /*Email of the student */
    private String email;

    /*The enrollment associated with this student
    * One student can enroll in many course */
    @OneToMany(mappedBy = "student")
    List<Enrollment> enrollmentList;
}
